<?php
/**
 * Created by PhpStorm.
 * User: Gonzalo V
 * Date: 24/11/2018
 * Time: 06:39 PM
 */
use Proyecto\Core\App;
use Proyecto\Session\Session;

if (Session::has('logueado') && Session::get('logueado')=='S') {
    $usuarioLogueado = true;
}else{
    $usuarioLogueado = false;
}

?>
<main class="py-4 mb-4 preguntas-frecuentes">
    <div class="container">
        <div class="row">
            <div class="col-md-2">
            </div>
            <div class="col-md-8">

                <h2 class="mt-5 mb-5 pfgreen">Términos y condiciones de uso del Sitio</h2>
                <p>El acceso y uso de nuestro sitio web www.proximafecha.com (el "Website") por cualquier visitante, usuario, proveedor, licenciatario o anunciante ("Usted", "Usuario" o "Usuarios") se encuentran sujetos al cumplimiento de los siguientes Términos y Condiciones de Uso ("Términos y Condiciones") y a toda otra legislación aplicable.</p>

                <h3>Aceptación de los términos y condiciones mediante el solo uso del website</h3>
                <p>Tanto el acceso como el uso del Website, y/o de los servicios ofrecidos en el mismo, constituyen la aceptación, sin limitación y/o excepción alguna, de estos Términos y Condiciones y el reconocimiento que cualquier otro acuerdo anterior que para el uso del Website, Usted pudiera tener con proximafecha.com queda anulado y sin fuerza legal alguna</p>
                <p>Si no está de acuerdo con los presentes Términos y Condiciones, por favor no utilice este Website. En dicho caso, no contará con la autorización para el uso de los servicios y contenidos publicados en el Website.</p>
                <p>Proximafecha.com se reserva el derecho de modificar los presentes Términos y Condiciones y el continuo uso del Website en cualquier momento. El Usuario deberá mantenerse actualizado en cuanto a los cambios que pudieran generarse en los presentes Términos y Condiciones revisando periódicamente los mismos. El continuo uso del Website constituye la aceptación de los Términos y Condiciones modificados. Proximafecha.com se reserva el derecho de terminar el uso de cualquier Usuario del Website en cualquier momento sin notificación previa, ya sea por una violación de los presentes Términos y Condiciones, de otras instrucciones de uso incluidas en este Website, y/o la normativa legal aplicable. Los datos e información proporcionados por los Usuarios serán tratados en un todo de acuerdo a las Políticas de Privacidad del Website.</p>

                <h3>Licencia de Uso de este Website</h3>
                <p>Proximafecha.com, titular y operador del Website, le otorga una licencia no-exclusiva, personal, intransferible y limitada para usar este Website estrictamente de conformidad con los presentes Términos y Condiciones y conforme se lo permite en las demás instrucciones del Website. </p>
                <p>Para la utilización de algunos servicios o acceso a ciertos contenidos del Website podrá establecerse como requisito el previo registro del Usuario. Dicho registro tendrá como finalidad conocer la identidad e información del Usuario. La información proporcionada por el Usuario deberá ser fidedigna, verdadera, exacta, actual y completa y poseerá el carácter de declaración jurada. El Usuario será responsable por mantener y actualizar la información proporcionada para que la misma continúe siendo fidedigna, verdadera, exacta, actual y completa. En este sentido, Usted acuerda no realizar ninguna declaración falsa o fraudulenta para acceder o usar el Website. En caso de declaraciones falsas o fraudulentas, el Usuario será responsable por los daños y perjuicios que su accionar pudiera generar a proximafecha.com o a terceros. </p>
                <p>Usted acuerda que todos los contenidos y servicios disponibles en este Website son de propiedad exclusiva de proximafecha.com y sus anunciantes y licenciatarios y que los mismos se encuentran protegidos por derechos de autor, marcas, secretos comerciales, y otros derechos de propiedad intelectual y leyes, en la Argentina e internacionalmente. Todos los derechos no expresamente otorgados mediante los presentes Términos y Condiciones en favor del Usuario quedan reservados en favor de proximafecha.com, sus anunciantes y licenciatarios, según corresponda.</p>

                <h3>Restricciones de Licencia</h3>
                <p>Mediante la aceptación de los presentes Términos y Condiciones, proximafecha.com le concede al Usuario una licencia para el uso del producto, desarrollado por proximafecha.com, por el período de vigencia estipulado en el Website y bajo los presentes Términos y Condiciones.</p>
                <p>El Website sólo puede ser usado conforme se lo dispone en los presentes Términos y Condiciones. Sus contenidos no pueden ser distribuidos, modificados, alterados, transmitidos, utilizados, reutilizados, o reenviados con fines comerciales o públicos, incluyendo el texto, las imágenes, audio y/o video allí contenidos, sin la previa y expresa autorización de proximafecha.com.</p>
                <p>En caso que Usted descargue o utilice software ofrecido por proximafecha.com a través del Website, el software, y los archivos, imágenes incorporadas en, o generadas por, el software, y los datos que acompañen al software (conjuntamente "Software"), le son otorgados a Usted bajo licencia de proximafecha.com o de terceros licenciantes, como fuese el caso, exclusivamente para su uso personal, no comercial y doméstico. proximafecha.com no le transfiere al Usuario la titularidad sobre ninguna parte del Software. Usted no podrá de ninguna otra manera redistribuir o explotar todo o parte del Software, ni descompilar, realizar ingeniería inversa, desarmar o reducir de forma alguna el Software a un formato susceptible de ser leído.</p>
                <p>Excepto como le fuese expresamente permitido en los presentes Términos y Condiciones, el Usuario se compromete a no guardar, descargar, copiar y pegar, vender, licenciar, alquilar, arrendar, modificar, distribuir, copiar, reproducir, transmitir, mostrar públicamente, ejecutar públicamente, publicar, adaptar, modificar o crear trabajos derivados del material, código o contenido del Website o cualquiera de los Micrositios de Campeonatos. La recuperación sistemática de datos u otros contenidos de este Website o cualquiera de los Micrositios para crear o compilar, directa o indirectamente, una colección, compilación, base de datos o directorio de cualquier tipo sin el permiso escrito de proximafecha.com se encuentra totalmente prohibida. De la misma forma, el uso de los contenidos o materiales del Website o cualquier Micrositio de Proximafecha.com para cualquier propósito que no esté expresamente permitido en los presentes Términos y Condiciones se encuentra terminantemente prohibido.</p>
                <p>El Usuario es el único responsable por los problemas resultantes del uso incorrecto del Website, cualquier Micrositio de Proximafecha.com o el Software.</p>

                <h3>Seguridad</h3>
                <p>Una vez registrados, los Usuarios dispondrán de nombre de Usuario y una contraseña que le permitirá el acceso seguro a su cuenta personal dentro del Website. El nombre de Usuario y la contraseña ingresada solo podrán ser utilizados exclusivamente por el Usuario registrado, quien se obliga a mantener dicha información de forma estrictamente confidencial y, consecuentemente, a impedir que terceros accedan al Website utilizando esa información. El Usuario asumirá la obligación de guarda y custodia de su nombre de Usuario y contraseña. El Usuario deberá notificar inmediatamente a proximafecha.com en caso de pérdida de esta información o acceso no autorizado por un tercero que no se encuentre bajo su control o supervisión.</p>

                <h3>Información de los productos y del servicio. Validez de las Promociones</h3>
                <p>La información sobre los servicios que provee proximafecha.com y condiciones de comercialización es suministrada al Usuario en forma gratuita, cierta, clara y detallada a través del Website.</p>

                <h3>Información de Productos y Serivicios Ofrecidos por Anunciantes</h3>
                <p>Proximafecha.com no está obligado a controlar, ni se hace responsable por el contenido disponible en el Website publicado por oferentes de bienes y/o servicios (los "Anunciantes"), ni por los usuarios del Website, ni por las pérdidas o daños que dicho contenido pueda causar a los Usuarios. Proximafecha.com no garantiza de modo alguno que no existan otros bienes y/o servicios en el mercado, que cumplan la misma función o que resulten más convenientes, en precio o condiciones, que los publicados en el Website. En consecuencia, proximafecha.com sugiere que la información respecto de los bienes y/o servicios publicados por los Anunciantes en el Website, sea objeto de investigación propia e independiente de quien esté interesado en aquellos, no asumiendo proximafecha.com ningún tipo de responsabilidad por la veracidad o exactitud de la información.</p>

                <h3>Prohibiciones</h3>
                <p>Se les prohíbe terminantemente a los Usuarios:</p>
                <ul>
                    <li>Enviar archivos o cualquier tipo de información cuyo contenido sea ilegal, obsceno, abusivo, difamatorio, injurioso o contrario a las buenas costumbres.</li>
                    <li>Enviar archivos que contengan virus o cualquier otra característica capaz de dañar el funcionamiento de un ordenador, del Website, de cualquier Micrositio de Campeonatos, o del sistema.</li>
                    <li>Utilizar el Website para violar cualquier tipo de norma vigente.</li>
                    <li>Colocar el nombre de una persona, como integrante de un equipo sin que éste haya prestado su autorización expresa. Si el integrante del equipo decidiese iniciar acciones legales por uso indebido de su nombre, el organizador del campeonato en cuestión será el responsable legal sobre quien deberán accionar. proximafecha.com no está obligado a controlar, ni se hace responsable por el contenido disponible en el Website.</li>
                    <li>Usar programas, software o aparatos automáticos o manuales para monitorear o copiar la información o cualquier contenido del sitio sin previo consentimiento de proximafecha.com.</li>
                </ul>

                <h3>Contenido al que se accede a través de Enlaces desde el Website y Resultados de Búsqueda</h3>
                <p>En el Website existen enlaces a otros sitios que llevan al Usuario a sitios fuera de nuestro control, tales como enlaces de anunciantes, patrocinadores y socios de contenido. Usted reconoce que al cliquear sobre cualquiera de los mencionados enlaces, los sitios a los que llegue no se encuentran controlados por proximafecha.com. En ese caso, resultarán aplicables otros términos de uso que desconocemos y por los cuales proximafecha.com no se hace responsable. Proximafecha.com no garantiza, respalda, patrocina, ni puede asegurar que Usted quedará satisfecho con ninguno de los productos o servicios que adquiera o utilice en sitios de terceros enlazados con el Website o con el contenido de terceros que se encuentre disponible en el Website. Recomendamos firmemente llevar a cabo cualquier investigación que considere necesaria o apropiada antes de realizar cualquier transacción con terceros. proximafecha.com tampoco se responsabiliza por la exactitud, veracidad, decencia o legalidad del contenido de los sitios a los que un Usuario pudiese acceder como resultado de búsquedas realizadas a través del Website.</p>

                <h3>Cláusula Exonerativa</h3>
                <p>El contenido en, o de alguna otra manera relacionado con, el Website o sitios de terceros o servicios enlazados desde el Website se provee "tal como está" y sin garantía de ninguna clase. En la mayor medida permitido por la ley aplicable, proximafecha.com desconoce todas las garantías, expresas o implícitas, incluyendo garantías de comerciabilidad, adecuación a un fin determinado, exactitud, condición de estar completo, disponibilidad, seguridad y compatibilidad. proximafecha.com no garantiza que ningún contenido esté libre de error, que el acceso al mismo será ininterrumpido, que los defectos sean corregidos o que el Website o los servidores que pongan a disposición dichos contenidos se encuentren libres de virus u otros componentes perjudiciales. Usted asume el costo de todos los servicios o piezas que fuesen necesarios para mantener, reparar o corregir su ordenador como consecuencia del uso del Website. Proximafecha.com no garantiza ni efectúa ninguna declaración con respecto al uso o los resultados del uso de ningún contenido. Por el presente, Usted renuncia en forma irrevocable a todo reclamo en contra de proximafecha.com respecto de los contenidos en el Micrositio de Proximafecha.com y cualquier contenido que Usted suministre a sitios de terceros (incluyendo información sobre tarjetas de crédito o cualquier otra información personal).</p>
                <p>El Website podrá contener la opinión y puntos de vista de otros Usuarios. Teniendo en cuenta la naturaleza interactiva de estos sitios, proximafecha.com no puede avalar, garantizar o ser responsable por la certeza, exactitud, completitud, o veracidad de cualquier contenido generado por los Usuarios del Website.</p>

                <h3>Indemnización</h3>
                <p>Usted se compromete a indemnizar, defender y mantener a salvo a proximafecha.com, así como a sus licenciantes, licenciatarios, distribuidores, agentes, representantes y demás usuarios autorizados y los respectivos revendedores, distribuidores, prestadores de servicios y/o proveedores de cada una de las entidades mencionadas, y a todos los respectivos funcionarios, directores, propietarios, socios, accionistas, empleados, agentes, representantes y cesionarios de las entidades mencionadas (conjuntamente "Partes Indemnizadas") por y contra cualesquier y todas las pérdidas, daños y perjuicios, responsabilidades y costos (incluyendo costos de arreglo y honorarios legales u otros y gastos de investigación o defensa de cualquier acción o amenaza de acción) incurridos por las Partes Indemnizadas en relación con cualquier reclamo que surja de un incumplimiento por parte de un Usuario de estos Términos y Condiciones o reclamos que surjan del uso del Website por parte de un Usuario. En este sentido, Usted se obliga a cooperar con proximafecha.com en la defensa de cualquier reclamo. Proximafecha.com se reserva el derecho, a su propio costo, de contratar un asesor independiente y asumir la defensa y control exclusivos de cualquier asunto que se encuentre sujeto a ser indemnizado por Usted.</p>
                <h3>Límite de la responsabilidad</h3>
                <p>Bajo ninguna circunstancia, incluyendo negligencia, proximafecha.com, sus licenciantes o licenciatarios o los respectivos revendedores, distribuidores, prestadores de servicios y/o proveedores de cada una de las entidades mencionadas, serán responsables hacia Usted o cualquier otra persona o entidad por daños mediatos, inmediatos, o eventuales, incluyendo lucro cesante, daños personales (incluso muerte) y daños a los bienes de cualquier naturaleza, cuando sean el resultado de (a) el uso de, o la imposibilidad de usar, el Website o su contenido o (b) la conducta o actos de algún usuario del Website o cualquier otra persona o entidad, aun cuando se hubiere notificado de la posibilidad de tales daños. En ningún caso podrá la responsabilidad total de proximafecha.com hacia Usted por todos los daños y pérdidas ocasionadas, por responsabilidad contractual o extracontractual (incluyendo por negligencia) o de cualquier otra índole, superar el monto abonado por Usted, de corresponder, o U$S 100 (Cien Dólares Estadounidenses), lo que resulte menor, por la posibilidad de acceder o participar en cualquier actividad o servicio relacionado con el Website. Además, bajo ninguna circunstancia podrá proximafecha.com, sus licenciantes y licenciatarios, o los respectivos revendedores, distribuidores, prestadores de servicios y/o proveedores de cualquiera de las entidades mencionadas, ser considerados responsables por demoras o faltas de cumplimiento que, directa o indirectamente, resulten de un acto de caso fortuito o fuerza mayor, fuera del control de proximafecha.com o las otras partes mencionadas más arriba.</p>
                <p>Proximafecha.com podrá terminar su acceso al Website o modificar el Website o eliminar cualquier contenido, en cualquier momento y por cualquier motivo, sin que implique responsabilidad alguna.</p>
                <p>Las limitaciones, exclusiones y exoneraciones contenidas en esta sección y en cualquier sección de estos Términos y Condiciones se aplican con el máximo alcance permitido por la ley aplicable.</p>
                <h3>Jurisdicción y Competencia</h3>
                <p>Los presentes Términos y Condiciones se encuentran regidos sin excepción y en todos sus puntos por las Leyes de la República Argentina y serán interpretados de acuerdo a las mismas.</p>
                <p>Ante cualquier diferencia, desacuerdo o conflicto derivado de la interpretación, validez, alcance y/o aplicación de los presentes Términos y Condiciones, los Usuarios se comunicarán con proximafecha.com de manera fehaciente, haciéndole llegar su reclamo a la dirección de e-mail info@proximafecha.com, para que las partes traten de arribar a un acuerdo.</p>
                <p>En caso de que no sea posible arribar a una solución, y para garantizar a los Usuarios el pleno acceso a la justicia, los Usuarios podrán elegir y someter su reclamo a una de las siguientes opciones e instancias:</p>
                <ol>
                    <li>
                        <p>Sistema nacional de arbitraje de consumo del Ministerio de Economía y Finanzas Públicas de la Nación. Los procedimientos ante este sistema son gratuitos, y no es necesario contar con un patrocinio letrado. Asimismo, se garantiza el equilibrio entre las partes y la transparencia en el proceso, y los laudos emitidos por dicho tribunal tienen autoridad de cosa juzgada y son irrecurribles (para saber más sobre este sistema ingresar en http://www.consumidor.gov.ar);</p>
                    </li>
                    <li>
                        <p>Dirección General de Defensa y Protección del Consumidor del Gobierno de la Ciudad de Buenos Aires (para saber más sobre este sistema ingresar en http://www.buenosaires.gov.ar); o</p>
                    </li>
                    <li>
                        <p>Tribunales ordinarios de la capital federal con competencia en la materia.</p>
                    </li>
                </ol>
                <p>Asimismo, el Usuario podrá comunicarse con proximafecha.com en cualquier momento a los efectos de llegar a un acuerdo enviando un correo electrónico a info@proximafecha.com.</p>
                <p>Proximafecha.com no efectúa ninguna declaración acerca de que el contenido del Website sea apropiado o esté disponible para ser usado en un lugar determinado. Quienes elijan acceder al Website lo hacen por su propia iniciativa y son responsables del cumplimiento de todas las leyes aplicables, incluyendo cualesquiera leyes locales que correspondan.</p>

                <h3>Disposiciones Generales</h3>
                <p>Si alguna disposición de estos Términos y Condiciones fuese ilegal, nula o por cualquier motivo inoponible, se considerará que dicha disposición es divisible de estos Términos y Condiciones y no afectará la validez u oponibilidad de ninguna de las disposiciones restantes. La renuncia de una disposición de estos Términos y Condiciones por parte de proximafecha.com no será considerada como una renuncia posterior o permanente de dicha disposición ni de ninguna otra disposición, y el hecho de que proximafecha.com no ejerza algún derecho o disposición bajo estos Términos y Condiciones no constituirá una renuncia de dicho derecho o disposición. En estos Términos y Condiciones, la palabra "incluyendo" se emplea en forma ilustrativa, como si estuviera seguida de la frase "sin limitación".</p>

                <h3>Políticas de Privacidad</h3>
                <p>Las políticas de privacidad de nuestro sitio web www.proximafecha.com (el "Website") tienen como fin informar a sus visitantes, ya sean usuarios, proveedores o anunciantes (colectivamente "Usuarios") respecto del tratamiento que proximafecha.com le brindará a la información que los mismos proporcionen en ocasión de la navegación por el Website, y sobre las diversas alternativas que los mismos poseen con respecto al uso de la misma.</p>
                <p>Las presentes políticas de privacidad (las "Políticas de Privacidad") podrán ser periódicamente modificadas por proximafecha.com a efectos de incluir el tratamiento de nuevos temas y a efectos de reflejar cambios en nuestro Website, como cambios en el tratamiento de la información proporcionada.</p>
                <p>Los Usuarios podrán acceder en todo momento a conocer el tipo de información recopilada y el tratamiento que proximafecha.com le brindará a la misma.</p>
                <ul>
                    <li>
                        <h4>Información personal</h4>
                        <p>Proximafecha.com recopilará a través del Website toda la información y datos que los Usuarios ingresen en su carácter de usuarios, proveedores o anunciantes, ya sean datos relacionados con su persona, su identidad o la de su empresa al registrarse al Website (la "Información Personal") o en el momento de contratar alguno de nuestros servicios. La Información Personal, que será necesaria recopilar para la funcionalidad de los servicios provistos en el Website, tendrá el carácter de confidencial y privada.</p>
                        <p>Como Usuario, usted consiente que su Información Personal sea tratada de la manera en la que se explica en estas Políticas de Privacidad.</p>
                    </li>
                    <li>
                        <h4>Alcance de las políticas de privacidad</h4>
                        <p>Estas Políticas de Privacidad serán aplicadas por proximafecha.com a su Website pero no resultarán aplicables a aquellos otros sitios a los que usted pudiera acceder por medio de links, o cualquier otro tipo de vínculo. En su caso, le sugerimos revisar atentamente las políticas de privacidad de esos sitios en cuestión.</p>
                    </li>
                    <li>
                        <h4>Uso de la información personal</h4>
                        <p>La Información Personal que los Usuarios pudieran proporcionar será tratada, de corresponder, por proximafecha.com en un todo de acuerdo con las disposiciones de la Ley de Protección de Datos Personales Nº 25.326 ("Ley Nº 25.326"), su decreto reglamentario y demás normas complementarias. La Información Personal que se requerirá a los Usuarios es aquélla información sin la cual se tornaría imposible brindar los servicios ofrecidos por el Website. Por dicho motivo, se requiere que ésta sea verdadera y exacta. En caso de que la Información Personal suministrada por el Usuario no sea verdadera, el Usuario será responsable por los daños y perjuicios que hubiera podido ocasionar. La Información Personal será utilizada con el propósito de identificar a los Usuarios. Asimismo, la Información Personal podrá ser utilizada con el propósito de personalizar y mejorar el Website, así como para establecer perfiles determinados con fines promocionales, comerciales o publicitarios; o que permitan establecer hábitos de consumo. A tal fin, se pone en su conocimiento que toda Información Personal proporcionada podrá será recopilada y almacenada en una base de datos de titularidad de proximafecha.com.</p>
                        <p>Los Usuarios, al suministrar Información Personal a través del Website, aceptan que proximafecha.com se comunique con ellos por cualquier medio de comunicación existente al presente o que pudiera implementarse en el futuro, incluyendo llamados telefónicos y/o correo electrónico, SMS, vía postal, telefónica o electrónicamente para el envío de informaciones y publicidades sobre productos y/o servicios de proximafecha.com (Marketing Directo) y cualquier otra información que proximafecha.com considere, a su exclusivo criterio, que pueda ser de su interés. En caso de que los Usuarios no deseen ser contactados con estos fines, podrán manifestarlo fehacientemente a proximafecha.com, quien procederá a interrumpir este tipo de comunicaciones con el menor tiempo que le sea posible.</p>
                        <p>En ningún caso proximafecha.com le solicitará a los Usuarios para su base de datos, información personal que revele el origen racial y étnico, opiniones políticas, convicciones religiosas, filosóficas o morales, afiliación sindical e información referente a la salud o a la vida sexual de los Usuarios ("Datos Sensibles").</p>
                        <p>Proximafecha.com podrá revelar la Información Personal a terceros sin su consentimiento solamente (i) cuando sea requerido por ley o por resolución judicial que así lo autorice; (ii) para cooperar con autoridades gubernamentales en investigaciones judiciales; (iii) para hacer cumplir o proteger la propiedad intelectual o derechos de proximafecha.com; y/o (iv) para poder ejecutar alguna de las obligaciones y/o compromisos y/o prestaciones vinculadas directa o indirectamente con estas Políticas de Privacidad o el uso del Website.</p>
                        <p>Asimismo, proximafecha.com podrá tomar la Información Personal identificable y hacerla no personalmente identificable, ya sea combinándola con otra información sobre otros individuos (agregando su información sobre otros individuos) o por remoción de características (tales como su nombre) que hacen de dicha información su Información Personal identificable (despersonalizando su información). Dada la naturaleza de esta información, no existen restricciones bajo estas Políticas de Privacidad respecto al derecho de proximafecha.com de agregar o despersonalizar la Información Personal de los Usuarios. proximafecha.com podrá utilizar y/o compartir con terceros la información que no resulte personalmente identificable resultante, de cualquier modo que lo considere conveniente.</p>
                        <p>Los Usuarios tienen la facultad de ejercer el derecho de acceso a su Información Personal en forma gratuita a intervalos no inferiores a seis (6) meses, a no ser que se acredite un interés legítimo al efecto conforme lo establecido en el artículo 14, inciso 3 de la Ley No. 25.326. A tal efecto, la Dirección Nacional de Protección de Datos Personales, órgano de control de la Ley No. 25.326, tiene la atribución de atender las denuncias y reclamos que se interpongan con relación al incumplimiento de las normas sobre protección de datos personales. Asimismo, los Usuarios podrán solicitar la modificación, eliminación, actualización y/o tratamiento confidencial de su Información Personal que se encuentre almacenada en la base de datos de proximafecha.com. Cualquier requerimiento a proximafecha.com por parte de los Usuarios de acceso, modificación, eliminación, actualización y/o tratamiento confidencial de la Información Personal provista, podrá efectuarse mediante el envío de dicho requerimiento a la dirección de e-mail: info@proximafecha.com. Una vez cumplido los extremos anteriormente detallados y si correspondiera hacer lugar a su pedido, proximafecha.com, le comunicará al Usuario si ha procedido a dar lugar o a rechazar su pedido. proximafecha.com tendrá diez (10) días hábiles desde la recepción de la solicitud para enviar una respuesta en caso de tratarse de una solicitud de acceso, y cinco (5) días hábiles si el Usuario solicitara la rectificación, actualización o supresión de sus datos.</p>
                        <p>La proporción por parte de los Usuarios de su Información Personal implica la aceptación de ser contactados por cualquier medio de comunicación existente al presente o que pudiese implementarse en el futuro, incluyendo llamados telefónicos y/o correo electrónico.</p>
                    </li>
                    <li>
                        <h4>Seguridad</h4>
                        <p>Proximafecha.com ha tomado todas las medidas posibles a su alcance a fin de asegurar la privacidad de la Información Personal proporcionada por los Usuarios.</p>
                    </li>
                    <li>
                        <h4>Destinatarios de la información personal</h4>
                        <p>Los Usuarios, al suministrar información a través del Website, aceptan que proximafecha.com pueda compartir dicha información con las empresas que contrate para la entrega de productos o servicios, como empresas de transporte que entregan los pedidos, call centers, empresas de atención al cliente o intermediarios en la gestión de pagos, entre otros. En dichas instancias existe la necesidad de compartir su información con dichas empresas. Con el objeto de otorgar un mejor servicio, proximafecha.com podrá ceder dicha información a empresas asociadas en el servicio ofrecido. Estas empresas están autorizadas a recopilar, recibir y utilizar información sólo a los efectos descriptos en este párrafo o conforme lo requiera la ley aplicable.</p></p>
                    </li>
                    <li>
                        <h4>Cookies</h4>
                        <p>El Website puede utilizar un sistema de seguimiento mediante "cookies", para que el acceso a la información, al pasar de página en página, se realice con mayor rapidez. En algunos casos, las "cookies" también pueden ayudar a identificar a los Usuarios, sin necesidad de solicitarles la clave de acceso una y otra vez.</p>
                        <p>Estas "cookies" son pequeños archivos que envía la página visitada y se alojan en el disco duro del ordenador del Usuario, ocupando poco espacio.</p>
                        <p>Se hace saber a los Usuarios que utilizando las opciones de su navegador podrán limitar o restringir según su voluntad el alojamiento de estas "cookies", aunque sea desaconsejable restringirlas totalmente.</p>
                        <p>Las "cookies" también podrán recoger información sobre las preferencias e intereses de los Usuarios. En el caso de que esto ocurra, la información será utilizada exclusivamente con fines estadísticos para mejorar los servicios que se prestan en el Website. proximafecha.com aplicará, en la mayor medida en que sea posible, procedimientos de disociación de la información de modo que los titulares de los datos sean inidentificables.</p>
                    </li>
                </ul>

                <h3>Vínculos con otros sitios</h3>
                <p>En el Website existen enlaces a otros sitios que llevan al Usuario fuera de nuestro servicio a sitios fuera de nuestro control, tales como publicidades de carteles y enlaces de los avisadores, patrocinadores y socios de contenido que están autorizados a usar nuestro(s) logo(s) como parte de una relación de asociación marcaria. Usted reconoce que al cliquear sobre cualquiera de los enlaces mencionados, los sitios a los que llegue no se encuentran controlados por proximafecha.com. En ese caso, resultarán aplicables otros términos de uso y políticas de privacidad que desconocemos y por los cuales proximafecha.com no se hace responsable.</p>

                <h3>Derechos reservados. Propiedad intelectual</h3>
                <p>Todos los derechos del presente Website están reservados y corresponden a proximafecha.com en virtud de los derechos de uso del dominio www.proximafecha.com.</p>
                <p>El contenido del presente Website, incluyendo aunque no limitado al texto, logos, gráficos y todo el diseño en general, así como su base de datos y software, es de propiedad o uso exclusivo de proximafecha.com y se encuentra protegido por la legislación nacional e internacional vigente sobre propiedad intelectual.</p>
                <p>Si el Usuario considera que el Website viola o atenta de algún modo contra derechos de propiedad intelectual de terceros, deberá notificarlo a proximafecha.com en la dirección de correo electrónico indicada en las presentes Políticas de Privacidad, acompañando toda la información y documentación necesaria que respalde la mencionada consideración.</p>

            </div>
            <div class="col-md-2">
            </div>
        </div>
    </div>
</main>


